version: "3.8"

services:
  bot:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env  # Load environment variables from .env file

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env  # Load database credentials from .env file
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
